# Generated by Django 4.2.30 on 2026-10-04 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlotFrameRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision_no', models.PositiveIntegerField(help_text='1-based revision sequence within the plot.')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('reviewed', 'Reviewed — ready to publish'), ('published', 'Published — a new sampling frame version'), ('blocked', 'Blocked by unresolved pending items')], default='draft', max_length=10)),
                ('original_boundary', models.JSONField()),
                ('original_declared_area_ha', models.FloatField()),
                ('original_area_polygon_ha', models.FloatField()),
                ('original_crs_epsg', models.PositiveIntegerField()),
                ('boundary', models.JSONField()),
                ('declared_area_ha', models.FloatField()),
                ('area_polygon_ha', models.FloatField(help_text='Polygon area computed at creation; cross-check result is carried in the area_check payload.')),
                ('crs_epsg', models.PositiveIntegerField(help_text='CRS of the proposed boundary coordinates, stated explicitly with every revision.')),
                ('crs_note', models.CharField(blank=True, help_text='Free-text CRS statement (datum, zone, source survey).', max_length=300)),
                ('area_tolerance', models.FloatField(help_text='Relative tolerance used for the declared/polygon check.')),
                ('area_check', models.JSONField(help_text='{"relative_error", "within_tolerance", "detail"}')),
                ('content_checksum', models.CharField(help_text='SHA-256 of boundary+area+CRS — idempotent re-upload key.', max_length=64)),
                ('reason', models.CharField(blank=True, help_text='Human-given reason; mandatory before publication.', max_length=400)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['plot__code', 'revision_no'],
            },
        ),
        migrations.CreateModel(
            name='SamplingFrameVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(unique=True)),
                ('source', models.CharField(choices=[('baseline', 'Baseline frame from the original survey polygons'), ('plot_revision', 'Emitted by publishing a plot frame revision')], default='plot_revision', max_length=16)),
                ('plot_payload', models.JSONField()),
                ('note', models.CharField(blank=True, max_length=400)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_revision', models.ForeignKey(blank=True, help_text='Null for the baseline frame; the revision that emitted it.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='emitted_frames', to='inventory.plotframerevision')),
            ],
            options={
                'ordering': ['version'],
            },
        ),
        migrations.AddField(
            model_name='plotframerevision',
            name='emitted_frame',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plot_revisions', to='inventory.samplingframeversion'),
        ),
        migrations.AddField(
            model_name='plotframerevision',
            name='plot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='frame_revisions', to='inventory.plot'),
        ),
        migrations.AddField(
            model_name='plotframerevision',
            name='supersedes',
            field=models.ForeignKey(blank=True, help_text='The previously published revision (null = original survey).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by', to='inventory.plotframerevision'),
        ),
        migrations.CreateModel(
            name='FrameIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('area_mismatch', 'Declared area outside tolerance of polygon area'), ('tree_excluded', 'New boundary excludes an existing stem position'), ('overlap', 'Boundary overlaps a same-stratum neighbour plot')], max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open — blocks publication'), ('resolved', 'Resolved by a later validation')], default='open', max_length=10)),
                ('detail', models.CharField(max_length=600)),
                ('payload', models.JSONField(blank=True, default=dict, help_text='Machine-readable detail: excluded stems, overlap area, areas, etc.')),
                ('fingerprint', models.CharField(help_text='Stable hash of kind+payload so re-validation reuses rows.', max_length=64)),
                ('resolution_note', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issues', to='inventory.plotframerevision')),
            ],
            options={
                'ordering': ['revision__plot__code', 'revision__revision_no', 'id'],
            },
        ),
        migrations.AddField(
            model_name='estimateversion',
            name='frame',
            field=models.ForeignKey(blank=True, help_text='The published sampling-frame version (plot boundaries and areas) this estimate is computed against. Explicit, never silently switched by a later boundary revision.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='estimates', to='inventory.samplingframeversion'),
        ),
        migrations.AddConstraint(
            model_name='plotframerevision',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'published'), _negated=True), fields=('plot',), name='uniq_one_open_revision_per_plot'),
        ),
        migrations.AlterUniqueTogether(
            name='plotframerevision',
            unique_together={('plot', 'revision_no')},
        ),
        migrations.AlterUniqueTogether(
            name='frameissue',
            unique_together={('revision', 'fingerprint')},
        ),
    ]
