# Generated by Django 4.2.30 on 2026-10-04 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlotFrameRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision_no', models.PositiveIntegerField(help_text='1-based edition number per plot.')),
                ('status', models.CharField(choices=[('draft', 'Draft — resurveyed boundary under check'), ('reviewed', 'Reviewed — human QA done, awaiting publication'), ('published', 'Published — the current sampling frame; immutable')], default='draft', max_length=10)),
                ('declared_area_ha', models.FloatField()),
                ('boundary', models.JSONField(help_text='Proposed boundary ring [[x_m, y_m], ...] in crs_epsg.')),
                ('polygon_area_ha', models.FloatField(help_text='Shoelace area of boundary in ha at draft creation.')),
                ('area_check', models.JSONField(default=dict, help_text='Area cross-check result: declared/polygon/relative diff/tolerance/passed.')),
                ('crs_epsg', models.IntegerField(help_text='Explicit CRS statement for this resurvey (EPSG code).')),
                ('crs_note', models.CharField(blank=True, help_text='Surveyor/CRS explanation travelling with this edition.', max_length=240)),
                ('geometry_checksum', models.CharField(help_text='SHA-256 of the canonical proposed ring. Identifies same geometry across editions (old/new comparison).', max_length=64)),
                ('content_checksum', models.CharField(help_text='SHA-256 of ring + declared area + CRS statement. An identical re-upload is idempotent (returns this edition); a same-ring area/CRS correction is a NEW edition.', max_length=64)),
                ('reason', models.CharField(blank=True, help_text='Why this revision exists (boundary resurvey reason).', max_length=400)),
                ('validation_payload', models.JSONField(default=dict, help_text='Full check output: area, CRS, excluded stems, overlaps.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.CharField(blank=True, max_length=400)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('publication_reason', models.CharField(blank=True, help_text='Mandatory documented reason for publication.', max_length=400)),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='frame_revisions', to='inventory.plot')),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by', to='inventory.plotframerevision')),
            ],
            options={
                'ordering': ['plot__code', '-revision_no'],
            },
        ),
        migrations.CreateModel(
            name='FrameRevisionIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('excluded_tree', 'New boundary excludes an existing stem position'), ('area_mismatch', 'Declared area vs polygon area beyond tolerance'), ('overlap', 'Overlaps another plot of the same stratum'), ('crs_mismatch', 'CRS statement differs from the station survey CRS')], max_length=20)),
                ('detail', models.JSONField(default=dict, help_text='Structured finding (tree label/coords, areas, other plot code, overlap fraction, CRS codes…).')),
                ('summary', models.CharField(max_length=400)),
                ('status', models.CharField(choices=[('open', 'Open — blocks publication'), ('resolved', 'Resolved by a documented human decision')], default='open', max_length=10)),
                ('resolution_note', models.CharField(blank=True, max_length=400)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='inventory.plotframerevision')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='estimateversion',
            name='frames',
            field=models.ManyToManyField(help_text='Plot frame editions this estimate is explicitly bound to.', related_name='estimates', to='inventory.plotframerevision'),
        ),
        migrations.AddField(
            model_name='treemeasurement',
            name='collected_frame',
            field=models.ForeignKey(blank=True, help_text='Published frame edition in force when this was observed.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='measurements_collected', to='inventory.plotframerevision'),
        ),
        migrations.AddConstraint(
            model_name='plotframerevision',
            constraint=models.UniqueConstraint(fields=('plot', 'revision_no'), name='frame_revision_no_unique_per_plot'),
        ),
        migrations.AddConstraint(
            model_name='plotframerevision',
            constraint=models.UniqueConstraint(fields=('plot', 'content_checksum'), name='frame_content_checksum_unique_per_plot'),
        ),
        migrations.AddConstraint(
            model_name='plotframerevision',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'published')), fields=('plot',), name='frame_one_published_per_plot'),
        ),
        migrations.AddConstraint(
            model_name='framerevisionissue',
            constraint=models.UniqueConstraint(fields=('revision', 'kind', 'summary'), name='frame_issue_unique_per_revision_kind_target'),
        ),
    ]
