# Generated by Django 4.2.30 on 2026-10-04 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_plotframerevision_framerevisionissue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plotframerevision',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft — resurveyed boundary under check'), ('reviewed', 'Reviewed — human QA done, awaiting publication'), ('published', 'Published — the current sampling frame; immutable'), ('superseded', 'Superseded — a previously published edition, retained as history')], default='draft', max_length=10),
        ),
    ]
